name: 'Docker Build and Push'
description: 'Build and push Docker images with Slack notification'

inputs:
  dockerfile-tag:
    description: 'Tag to replace in Dockerfile'
    required: true
  docker-tags:
    description: 'Newline-separated list of Docker tags'
    required: true
  slack-title:
    description: 'Title for Slack notification'
    required: true
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub token'
    required: true
  buildcloud-endpoint:
    description: 'Buildcloud endpoint'
    required: true
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: ${{ inputs.buildcloud-endpoint }}

    - name: Update Dockerfile
      shell: bash
      run: sed -i "s/@ngiab_dev/@ngiab_$(echo ${{ inputs.dockerfile-tag }} | sed 's/\./\\./g')/g" ./docker/Dockerfile

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.docker-tags }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ngen-github-ci
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://avatars.githubusercontent.com/u/119541160?s=48&v=4
        SLACK_TITLE: ${{ inputs.slack-title }}
        SLACK_USERNAME: Github Action Result
        SLACK_WEBHOOK: ${{ inputs.slack-webhook-url }}
